### ISSUE TITLE
documentation list wrong dependency 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-validation#106]
### Issue description

We say: 

`jakarta.validation:validation-api` 

however, dependency is: 

`jakarta.validation:jakarta.validation-api`

**Comment by wetted** [comment]
Ha...looks like I got it wrong in the starter `MicronautValidationFeature` too (I used these docs). I'll fix that too.

**Comment by sdelamo** [comment]
> Ha...looks like I got it wrong in the starter `MicronautValidationFeature` too (I used these docs). I'll fix that too.

I fixed that here https://github.com/micronaut-projects/micronaut-starter/pull/1744
