### ISSUE TITLE
Obtain information from custom annotation that allows the user to specify validation error property path

### ISSUE THREAD

**Issue by cpichei** [micronaut-projects/micronaut-validation#115]
### Feature description

This feature will make it easier for developers to specify a POJO's path where a specific validation error occurred.

Some JavaScript validation frameworks (like Vee-validate) allows linking validation errors that are returned from a web service to fields on a form. But, for this to work, it is necessary that these errors contain information about where the different validation errors happened.

I tried using the Micronaut Validation API (without using micronaut-hibernate-validator module) to access annotation properties that would make it easier to identify the POJO path where the validation error happened, but I was not successful. Take into consideration the following example:

```
@Constraint(validatedBy = {})
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface UniqueDocumentId {
    String path() default "documentId";

    String message() default "This document ID already exists";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}

```

And we could use it on a POJO like this:

```
@UniqueDocumentId(path="documentId")
public class Person(){
@Id
private Integer id;

private String documentId;
}
```

I could then access the `path` field from this annotation in a custom BadRequestExceptionHandler that compiles the validation errors as well as where they happened like this:

```
@Produces
@Singleton
@Replaces(value = ConstraintExceptionHandler.class)
@Requires(classes = {ConstraintViolationException.class})
public class BadRequestExceptionHandler implements ExceptionHandler<ConstraintViolationException,
        HttpResponse<ValidationError>> {

    private final ErrorResponseProcessor<?> errorResponseProcessor;

    public BadRequestExceptionHandler(ErrorResponseProcessor<?> errorResponseProcessor) {
        this.errorResponseProcessor = errorResponseProcessor;
    }

    @Override
    public HttpResponse<ValidationError> handle(HttpRequest request, ConstraintViolationException ex) {

        final Map<String, List<String>> errorResponse =
                ex.getConstraintViolations()
                        .stream()
                        .collect(Collectors.groupingBy(o -> o.getAnnotationProperty("path"), Collectors
                                .mapping(ConstraintViolation::getMessage, Collectors
                                        .toList())));

        return errorResponseProcessor
                .processResponse(ErrorContext.builder(request)
                        .build(), HttpResponse.badRequest())
                .body(new ValidationError(errorResponse));
    }
}
```

Now, to make this easier to work, something must be done about constraint annotations that must be specified at the class level, as sometimes one needs to specify if a unique piece of data exists but has to take into account if a different person exists in the database for UPDATE operations to avoid having a validation error on a POJO because one got a hold of the document id for the person for which an UPDATE operation is requested (this is easy to solve if one runs a query that takes into account the id of the entity for which the UPDATE operation is executed, hence the need of class level validation). If we had something like above, we could specify this path variable and, no matter where it is placed, we will be able to get the specified variable and output this information on the JSON that describes the different validation errors.

**Comment by dstepanov** [comment]
The path should be provided by:
```java
	/**
	 * @return the property path to the value from {@code rootBean}
	 */
	Path getPropertyPath();
```

**Comment by cpichei** [comment]
> The path should be provided by:
> 
> ```java
> 	/**
> 	 * @return the property path to the value from {@code rootBean}
> 	 */
> 	Path getPropertyPath();
> ```

This path is empty if one uses class level validation.

**Comment by dstepanov** [comment]
Why would you put it on the entity and not on the field?

**Comment by cpichei** [comment]
> Why would you put it on the entity and not on the field?

Because sometimes one would need to do cross-validation between multiple properties of the POJO. Consider the following situation:

There is a need to create a person registry application, which you can use to persist people's documentId as well as other personal information. Now, this application would need to support both INSERT's and UPDATE's. If you want to enforce that the documentId is unique for all entities, then the UPDATE operation is going to fail for those cases when you want to update any field but the documentId as the validation process would look in the database if there exists a person that has the same documentId as the person whose information you are updating.

A possible solution to this problem is to not only do a lookup for this documentId, but also on the Id of the entity to discard the person whose data is being updated from throwing a @UniqueDocumentId validation error. In order to get at this @Id, one would place the annotation at the class level so that, on the custom ConstraintValidator, you would access this @Id and do a query similar to this: SELECT EXISTS (SELECT 1 FROM Person p WHERE p.documentId = :documentId AND p.id is different from :id).

**Comment by cpichei** [comment]
As an addendum to this feature, one could modify the validation error collecting logic to this:

```
final Map<String, List<String>> errorResponse =
                ex.getConstraintViolations()
                        .stream()
                        .collect(Collectors.groupingBy(o -> o.getPropertyPath().toString().isBlank() || o.getPropertyPath().toString().isEmpty() ? o.getAnnotationProperty("path") : o.getPropertyPath().toString(), Collectors
                                .mapping(ConstraintViolation::getMessage, Collectors
                                        .toList())));
```

This will allow us to continue using property path for those annotations already included within the Micronaut Framework (like @Email, @Size, etc.,) which can be used without any problems on the majority of cases, while allowing to set the property of the POJO where validation failed whenever a class level constraint is used.

**Comment by dstepanov** [comment]
I think the correct solution would be to specify the path in the validator using the context https://jakarta.ee/specifications/platform/8/apidocs/javax/validation/constraintvalidatorcontext

```java
//From a class level constraint on Address
 //Build a constraint violation on the default path + "street"
 //i.e. the street property of Address
 context.buildConstraintViolationWithTemplate( "this detail is wrong" )
             .addPropertyNode( "street" )
             .addConstraintViolation();
```

But that is not implemented yet.

**Comment by cpichei** [comment]
Could this be implemented as a Map<String, Object> to make it easier to do validation error aggregation on property paths (for those cases in which you have multiple failing validations on a single property)?

**Comment by dstepanov** [comment]
What do you mean? The build context can produce multiple violations

**Comment by cpichei** [comment]
> What do you mean? The build context can produce multiple violations

Yeah I understand that. What I meant is, for those cases where one has multiple constraint validations on a single property, if we could do an aggregation of all the validation errors based on the property name we could have a validation error JSON structure like the following:

```
errors: {
    documentId: ["validation error 1", "validation error 2"],
    personName: ["validation error 1", "validation error 2", "validation error 3"]
}
```
Using the Java streaming API, we could achieve this easily if we could query either the propertyPath, or a Map<String, Object> where each element of this map contains a keyvalue-pair like 'Annotation property', 'Annotation property value' that allows us to aggregate on this K,V pair.

**Comment by dstepanov** [comment]
The path should be provided manually in your custom validator, we can probably provide a way to access annotation metadata in the exception, but I don't think it's needed in this use-case.
