### ISSUE TITLE
Micronaut 4.x: Validation of POJOs in collection stopped working

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-validation#194]
### Expected Behavior

With MN:3.9/3.10, validation works with the following data classes (please see tests in main branch in example repo) 

```
import io.micronaut.core.annotation.Introspected
import javax.validation.Valid
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern

@Introspected
data class CompanyIdVm(

    @field:Pattern(regexp = "\\d{9}", message = "Some validation message")
    val companyId: String
)

@Introspected
data class MyFormVm(
    @field:Min(value = 2022, message = "Year cannot be less than {value}")
    val year: Int,

    @field:Valid // not working with Micronaut:4.x
    val companyIds: Collection<CompanyIdVm>
)
```

### Actual Behaviour

In example repo, please switch to branch MN_4. After upgrading to MN:4, code looks like this:

```
import io.micronaut.core.annotation.Introspected
import jakarta.validation.Valid
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.Pattern

@Introspected
data class CompanyIdVm(

    @field:Pattern(regexp = "\\d{9}", message = "Some validation message")
    val companyId: String
)

@Introspected(classes = [MyFormVm::class, Collection::class]) // required, else we get "No bean introspection ..."
data class MyFormVm(
    @field:Min(value = 2022, message = "Year cannot be less than {value}")
    val year: Int,

    @field:Valid // with MN:4, validation is not triggered for CompanyIdVm
    val companyIds: Collection<CompanyIdVm>
)
```
`ValidationTest` is no longer passing because `@field:Pattern(regexp = "\\d{9}", message = "Some validation message")` is not triggered.

Please note that this may be related to https://github.com/micronaut-projects/micronaut-validation/issues/33
but `Collection<@Valid CompanyIdVm>` is not working as well.

Temp-fix in controller where validator is injected `io.micronaut.validation.validator.Validator`
```
myFormVm.companyIds.flatMap { companyId ->
    validator.validate(companyId).iterator().asSequence()
}.takeIf { it.isNotEmpty() }?.let {
    throw ConstraintViolationException(it.toSet())
}
```

### Steps To Reproduce

1. Clone https://github.com/roar-skinderviken/micronaut-4-validation-issue
2. Switch to MN_4 branch
3. Run `mvn clean verify` and observe that test with name "MyFormVm that should fail validation"  is failing because only `@field:Min` is giving validation error.

### Environment Information

Ubuntu 22.04
JDK 17

### Example Application

https://github.com/roar-skinderviken/micronaut-4-validation-issue

### Version

4.0.4

**Comment by j1m-renwick** [comment]
I'm also seeing a lack of constraint validation in my Micronaut 4 Groovy project, which previously validated correctly as of Micronaut 3.9.0

**Comment by dstepanov** [comment]
Your project is incorrectly configured, it needs to be:
```
                                <path>
                                    <groupId>io.micronaut.validation</groupId>
                                    <artifactId>micronaut-validation-processor</artifactId>
                                    <version>${micronaut.validation.version}</version>
                                </path>
```
```
@Introspected
data class MyFormVm(
    @field:Min(value = 2022, message = "Year cannot be less than {value}")
    val year: Int,
    @field:Valid
    val companyIds: Collection<CompanyIdVm>
)
```

**Comment by roar-skinderviken** [comment]
@dstepanov If you switch to MN_4 branch, you will see that this i correctly configured. Can you please reopen this issue?

![image](https://github.com/micronaut-projects/micronaut-validation/assets/7499642/853a7aab-95ac-4742-9b85-ef0e614d2b6e)

**Comment by j1m-renwick** [comment]
Have raised the issue I am seeing as a separate bug ticket: https://github.com/micronaut-projects/micronaut-validation/issues/195
