### ISSUE TITLE
Custom Constraint validation not working in Micronaut 4

### ISSUE THREAD

**Issue by j1m-renwick** [micronaut-projects/micronaut-validation#195]
### Expected Behavior

Custom constraint validation is triggered for annotated fields

### Actual Behaviour

Custom validators do not get invoked

### Steps To Reproduce

1. Open and run [validation-bug.zip](https://github.com/micronaut-projects/micronaut-validation/files/12394276/validation-bug.zip)
2. make a POST API request to `http://localhost:8080/validate` with empty request body of:

```
{ }
```

And see the 400 request with the message `body.notNullField: must not be null` (proving that standard validation annotations are working as expected)

3. make a POST API request to `http://localhost:8080/validate` with request body of:

```
{
    "customConstraintField": "this should be invalid",
    "notNullField": "something"
}
```
And see a successful 202 response, showing that the custom validation annotation has not triggered.

### Environment Information

Operating System: MacOS Ventura, Version 13.4
JDK Version: Coretto 17

### Version

4.0.3

**Comment by dstepanov** [comment]
`MyConstraintValidator` needs to be `@Introspected`

**Comment by j1m-renwick** [comment]
thanks, that fixed it 👍   Is this documented somewhere or in the migration breaking change info?  I don't remember seeing it, and I don't know how I would have arrived at that fix without your input..

**Comment by dstepanov** [comment]
The scenario with `validatedBy` wasn't supported before, but you are right we should have it documented and probably support beans as the constraints.

**Comment by j1m-renwick** [comment]
ok cool, I'm happy to raise a PR to highlight it if you point me at the docs that you think need to be updated?

**Comment by dstepanov** [comment]
You can see in the docs we have the example from the previous version without `validatedBy`. We might want an example with it.

**Comment by j1m-renwick** [comment]
Raised a PR updating the documentation: https://github.com/micronaut-projects/micronaut-validation/pull/198
