### ISSUE TITLE
Custom validator are not discovered

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-validation#202]
### Expected Behavior

Reading the documentation custom validator should be discovered by creating class then registering it via service loader as explained here: https://micronaut-projects.github.io/micronaut-validation/snapshot/guide/#compileTimeValidation

By the way, as it's mandatory to use the annotation processor, registering a custom validator via a factory should no longer work so I wonder why it's still on the documentation.

### Actual Behaviour

Custom validators are not discovered and leads to exception like: `jakarta.validation.UnexpectedTypeException: Cannot find a constraint validator for constraint: com.example.validations.FlowValidation and type: class com.example.Flow`

I checked on the  validator from the application context and the list of validator didn't contains any custom one.

See the reproducer: 
[validation-superbuilder-issue.zip](https://github.com/micronaut-projects/micronaut-validation/files/12487859/validation-superbuilder-issue.zip)

### Version

4.0.5

**Comment by loicmathieu** [comment]
There is a test in the test project, running the test will generate the exception

**Comment by loicmathieu** [comment]
Reading https://github.com/micronaut-projects/micronaut-validation/pull/198 I added `@Singleton` and `@Introspected` to all my validators and they are now found by Micronaut but it seems that the standard ones are no longer found: `jakarta.validation.UnexpectedTypeException: Cannot find a constraint validator for constraint: jakarta.validation.constraints.NotBlank and type: class java.lang.Integer`

**Comment by dstepanov** [comment]
`NotBlank` cannot be applied to the integer

**Comment by loicmathieu** [comment]
Anyway I have tens of those issues, but maybe now that the validation is validated I need to fix all the validation that didn't pass the validation.

**Comment by dstepanov** [comment]
I think before it was simply ignored
