### ISSUE TITLE
Value extractors for container types not working (List, Map, Set, Optional)

### ISSUE THREAD

**Issue by KangoV** [micronaut-projects/micronaut-validation#261]
### Expected Behavior

When having a constraint on a container type, e.g.:
```
Optional<@Vocab(IDENTITY_CLASS) String> getIdentityClass();
```
I would expect the validation to occur.

### Actual Behaviour

The validator does not get called.

### Steps To Reproduce

Add a constraint to any container type and then validate. The validator never gets called.

### Environment Information

Mac OS 14
Java 17.0.2-tem
mn-validator 4.2.0

### Version

4.2.0

**Comment by dstepanov** [comment]
Pls create an example project

**Comment by KangoV** [comment]
I'm working on it at the moment. It's quite complex as it's STIX.

I think the problem may be the fact I am using the Immutables.io library to generated the implementations. The `@Vocab` constraint is in the interface and is noy copied to the implementation. Hibernate Validator seems to find it in the superclass. Maybe that is the problem?

**Comment by KangoV** [comment]
I've pushed the code:
```
git clone  https://github.com/KangoV/stixj/tree/mn-cal-bug-261
git checkout mn-cal-bug-261
```

Run `./gradlew test -i | grep "VOCAB"`, you will see the following log output:

```
    20:39:49.315 [Test worker] DEBUG i.k.stix.validation.VocabValidator - !VOCAB!
    20:39:49.320 [Test worker] DEBUG i.k.stix.validation.VocabValidator - !VOCAB!
```
This means the the `VocabValidator` has been called (it doesn't do anything else yet).

Now edit `io.kangov.stix.core.sdo.objects.Identity` and change the following code (line 103), from

```
    @JsonProperty("identity_class")
    @Redactable(useMask = true)
    @Vocab(IDENTITY_CLASS)
//    Optional<@Vocab(IDENTITY_CLASS) String> getIdentityClass();
    Optional<String> getIdentityClass();
```
to
```
    @JsonProperty("identity_class")
    @Redactable(useMask = true)
//    @Vocab(IDENTITY_CLASS)
    Optional<@Vocab(IDENTITY_CLASS) String> getIdentityClass();
//    Optional<String> getIdentityClass();
```
so that the constraint is no longer in the container type, but at the method level.
Now run `./gradlew test -i | grep "VOCAB"` again, you will not see those two log lines. This means that the validator is now not called.

I hope this makes sense.

**Comment by KangoV** [comment]
It does seem that there are extractors for 

* Iterable
* List
* Map Key
* Map Value

in `io.micronaut.validation.validator.extractors.InternalValueExtractors`

I'm wondering if they are just not activated? Or somehow just switched off?

**Comment by dstepanov** [comment]
We have known problem with generics annotations not being inherited. Can you try to duplicate then on the implementation?

**Comment by KangoV** [comment]
I simplified an example which demonstrates the constraint on a container type not being found:

```
@MicronautTest
public class ValidationTest {

    @Inject
    Validator validator;

    interface Interface {
        Optional<@Min(0) Integer> value();
    }

    @Introspected
    record Record(Optional<Integer> value) implements Interface {}

    @Test
    void test() {
        var violations = validator.validate(new Record(Optional.of(-1)));
        assertThat(violations).hasSize(1);
    }
}
```
This is basically what I have. I have `Record` implementing `Interface` which the Introspection on interface.

**Comment by KangoV** [comment]
Ok, it seems that bean Introspection is working:
```
Found BeanIntrospection for type: class io.kangov.stix.common.ValidationTest$Record
```
but, if I change the code to this:
```
@Min(0)
Optional<String> value();
```
I get....
```
jakarta.validation.UnexpectedTypeException: Cannot find a constraint validator for constraint: jakarta.validation.constraints.NotBlank and type: class java.util.Optional
	at io.micronaut.validation.validator.DefaultValidator.validateConstrains(DefaultValidator.java:1391)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:1109)
	at io.micronaut.validation.validator.DefaultValidator.visitElement(DefaultValidator.java:1047)
...
```

**Comment by dstepanov** [comment]
Where is the `@NotBlank` defined?

**Comment by KangoV** [comment]
Oop, not sure how that got there. I've updated the code above. I have created my own constraint and replace `@Min`. It gets called at the method level (for which I have to unwrap the optional, but is not found at all at the container level (if the constraint is in the interface).

If the constraint is on the actual record itself, it works: 
```
@Introspected
record Record(@Minimal(0) Optional<Integer> value) implements Interface {}
```
But as i am generating the implementation classes with Immutable.io, I cannot do that.

**Comment by dstepanov** [comment]
Can you please update your project with the failed example?

**Comment by KangoV** [comment]
Apologies for the delay. Trying to reorganise the project a bit better.

There are two objects to be aware of:
* `io.kangov.stix.v21.core.sdo.objects.Identity` - The interface that Immutables will create the implementation from
* `io.kangov.stix.v21.core.sdo.objects.IdentityImpl` - The generated implementation

The attribute under test is:
```
    @JsonProperty("roles")
    Set<@Size(min=2) String> getRoles();
```
There is a couple of assertions in test `io.kangov.stix.v21.core.sdo.objects.IdentityTest.test_Roles_below_min`.

The test simply injects the `Validator`, set the correct object state to (hopefully) trigger a violation and perform the validation.

The test fails.

Note that the generated `IdentityImpl` does have `Introspected` added.

All in same branch as before:
```
git clone https://github.com/KangoV/stixj/tree/mn-cal-bug-261
git checkout mn-cal-bug-261
./gradlew build
```
I hope this helps. Let me know if you need anything else.

**Comment by KangoV** [comment]
I've dug into this a little more. Given the following:

```
Set<@Vocab(PROCESSOR_ARCHITECTURE) String> getArchitectureExecutionEnvs();
```

@Vocab just tests to see if each element is in a given vocabulary of strings.

In `DefaultValidator` method `visitContainer`, there is this code:

```
if (!isValidated(containerArgument)) {
    return false;
 }
```
which calls `isValidated(containerArgument)`:
```
private <E> boolean isValidated(Argument<E> containerArgument) {
    return containerArgument.getAnnotationMetadata().hasAnnotation(ValidatedElement.class);
}
```
which always returns `false`.

The `containerArgument` is `Set architectureExecutionEnvs`.

The `isValidated(containerArgument)` returns false so the whole `visitContainer` method returns false, resulting in the container never getting validated.

Could this be the problem?

**Comment by KangoV** [comment]
I think the issue is that `ValidatedElement` is only used in the `DefaultValidator` and only in 2 test clauses. The text says that this annotation is used to trigger cascading. But, I cannot see anywhere in the code that adds that annotation to the metadata of an argument.

I would assume that i should never use this directly as it says it's for internal use only.

As this annotation is never present, container validation cannot take place.

**Comment by dstepanov** [comment]
`ValidationVisitor` is adding it, to simplify runtime traversal

**Comment by dstepanov** [comment]
If you use IntelliJ it will not show classes on the annotation processor classpath https://github.com/micronaut-projects/micronaut-validation/blob/master/validation-processor/src/main/java/io/micronaut/validation/visitor/ValidationVisitor.java

**Comment by dstepanov** [comment]
It looks like you are hitting a problem with annotations of generics not being inherited https://github.com/micronaut-projects/micronaut-validation/pull/228

**Comment by altro3** [comment]
@dstepanov @graemerocher you can close. It's already fixied
