### ISSUE TITLE
Unable to replace a ConstraintValidator

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-validation#278]
### Expected Behavior

We can replace a ConstraintValidator bean with another bean

### Actual Behaviour

A Constraint validator bean cannot be replaced by another one since Micronaut 4 (it works with Micronaut 3).

For ex given this ConstraintValidator:

```java
@Singleton
@Introspected
public class ExampleValidator implements ConstraintValidator<ExampleValidation, Object> {
    @Override
    public boolean isValid(@Nullable Object value, @NonNull AnnotationValue<ExampleValidation> annotationMetadata, @NonNull ConstraintValidatorContext context) {
        return false;
    }
}
```

If we provide another constraint validator for the same validation annotation that replaces the previous bean:

```java
@Singleton
@Introspected
@Replaces(ExampleValidator.class)
public class ExampleValidator2 implements ConstraintValidator<ExampleValidation, Object> {
    @Override
    public boolean isValid(@Nullable Object value, @NonNull AnnotationValue<ExampleValidation> annotationMetadata, @NonNull ConstraintValidatorContext context) {
        return true;
    }
}
```

The first validator is always used.

### Steps To Reproduce

This project reproduce the issue, calling the example endpoint always generate a validation error whereas it should not.

[validator-override.zip](https://github.com/micronaut-projects/micronaut-validation/files/13785505/validator-override.zip)

### Environment Information

0S: Linux *** #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Java: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)

### Version

4.2.2

**Comment by dstepanov** [comment]
Please try to remove `@Introspected`

**Comment by loicmathieu** [comment]
Thanks @dstepanov without the `@Introspected` annotation it works
