### ISSUE TITLE
[Micronaut 4] Validating Bean Methods is not Working as Mentioned in the Doc

### ISSUE THREAD

**Issue by moksie** [micronaut-projects/micronaut-validation#283]
### Issue description

We are migrating from Micronaut 3 to Micronaut 4. Currently, we are trying to use micronaut 4.2.3 along with micronaut-validation-4.2.0. With this setting, the bean method validations are not working as before and all the unit tests around this are failing.

Also as I was following the steps mentioned [here](https://micronaut-projects.github.io/micronaut-validation/latest/guide/index.html#methodsValidation), it turned out that the example is not working as well. While debugging this, I figured that the [conditional](https://github.com/micronaut-projects/micronaut-validation/blob/master/validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java#L887) prevents the validation. Based on this finding, I have added `@Validated` annotation to the service class and `@ValidatedElement` to each of the parameters with constraint as a workaround. The modified implementation of the service class mentioned in the doc looks like the following 
```
import io.micronaut.validation.Validated;
import io.micronaut.validation.annotation.ValidatedElement;
import jakarta.inject.Singleton;
import jakarta.validation.constraints.NotBlank;

@Singleton
@Validated
public class PersonService {
    public void sayHello(@ValidatedElement @NotBlank String name) {
        System.out.println("Hello " + name);
    }
}
```

After these modifications the following test is passing.
```
@MicronautTest(startApplication = false)
public class PersonServiceTest {
    @Inject
    PersonService personService;

    @Test
    void testThatNameIsValidated() {
        final ConstraintViolationException exception =
                assertThrows(ConstraintViolationException.class, () ->
                        personService.sayHello("") // (1)
                );

        assertEquals("sayHello.name: must not be blank", exception.getMessage()); // (2)
    }
}
```

I am using java 17.
```
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)
```

Am I missing something? Is there any better workaround for this?

**Comment by dstepanov** [comment]
You are missing the validation annotation processor.

**Comment by moksie** [comment]
@dstepanov Thanks a lot for the quick feedback. It helped to find the problem. The validation annotation processor was there, but the actual problem was that the Micronaut library plugin was missing from the build configuration. Surprised that validation was working with Micronaut 3 even with that missing configuration.
