### ISSUE TITLE
UnexpectedTypeException: Cannot find a constraint validator for constraint

### ISSUE THREAD

**Issue by mancze** [micronaut-projects/micronaut-validation#312]
### Expected Behavior

Validator should not throw the exception and behave uniformly on subsequent calls.

### Actual Behaviour

Exception is thrown when `validator.validate(validBean)` is being validated:

```
jakarta.validation.UnexpectedTypeException: Cannot find a constraint validator for constraint:
```

### Steps To Reproduce

Included in the example application including naive workaround. Run tests to identify bug.

1. Use Micronaut validation + Jakarta validation annotations
2. Declare a bean with validated properties
3. Inject Validator bean into your tests
4. Call `validator.validate()` with your valid bean
5. Exception is thrown
6. Catch it and re-run `validator.validate()`
7. No exception is thrown

Steps 5 and 7 produce inconsistent validation behaviour.

I think that possible cause is this line: https://github.com/micronaut-projects/micronaut-validation/blob/89efd63316fec41be03499b6ab969d8be92ffeb9/validation/src/main/java/io/micronaut/validation/validator/constraints/DefaultConstraintValidators.java#L151 

A `ConstraintValidator.VALID` is put to the validator's cache but `Optional.empty()` is returned. Subsequent calls of the method return the cached `ConstraintValidator.VALID` which is the reason of the inconsistent behaviour.

### Example Application

https://github.com/mancze/micronaut-sandbox/tree/repro/constraint-validation-not-found

### Version

4.3.2

**Comment by dstepanov** [comment]
The error is correct. You don't have a validator defined. Remove `@Constraint` if you want just to apply other constraints.

**Comment by mancze** [comment]
Also, I observe some inconsistency related to the validation cache. With `@Constraint(validatedBy = { })` annotation preserved and the test case being modified to:

```
try {
	assertThat(validator.validate(bean)).isEmpty();
} catch (Exception e) {
	// retry
	assertThat(validator.validate(bean)).isEmpty();
}
```
(https://github.com/mancze/micronaut-sandbox/commit/e311721c84520b2cff98db2ff930d6aaaa669328) 

then only the first validation fails and the second one in the catch block not. The behaviour is not consistent.
