### ISSUE TITLE
Micronaut 4: validation not working

### ISSUE THREAD

**Issue by ShaimaaSabry** [micronaut-projects/micronaut-validation#412]
### Expected Behavior

When calling `POST trips` the DTO gets validated and it returns 400 error because the fields are annotated with `NotNull`.

### Actual Behaviour

The DTO is not validated and it gets passed through to the controller resulting in a 500 null error.

### Steps To Reproduce

1. Open and run: [uber.zip](https://github.com/user-attachments/files/16979458/uber.zip)
2. Make a request to `POST ttp://localhost:8080/trips` with an empty body.
3. Returns a 500 null exception instead of a 400 validation error.

### Version

4.6.1

**Comment by davidsonnabend** [comment]
Looks like it has something to do with a current Micronaut Core bug with [ExceptionHandler](https://github.com/micronaut-projects/micronaut-core/issues/10808). 🤔

**Comment by dstepanov** [comment]
Please don't use Lombok if you don't know how to properly configure it.
